### ISSUE TITLE
Dark mode???????????????

### ISSUE THREAD

**Issue by gwerrry** [Breakfast-Galaxy-Studios/Soundboard#3]
pls add dark mode just like discord ;)

**Comment by MalTheLegend104** [comment]
If anyone stumbles across this and wants to try to add this before I do, all of the UI is assembled and styled in the UI class. Everything should have a gray or black background with white text. Things like tables should have white borders. If no one gets around to it before me, this will be released in the next major feature update.

**Comment by MalTheLegend104** [comment]
This will be apart of full release v2.0, currently included in pre-v2.0.
