### ISSUE TITLE
Adding sounds with the same name causes unexpected results.

### ISSUE THREAD

**Issue by gwerrry** [Breakfast-Galaxy-Studios/Soundboard#5]
Adding sounds with the same name gives a message that you can't add sounds, yet it still adds sounds.

**To Reproduce**
1. Create a sound with a name
2. Create a sound with the same name (case doesn't matter)

**Expected behavior**
A warning that says you cannot add the sound and lets you change the name of the sound before trying again.

**Desktop (please complete the following information):**
 - OS: Windows (should not matter)
 - OS Version: Windows 11 (should not matter)
 - Java Version: latest (17)

**Comment by MalTheLegend104** [comment]
Fixed in commit [08b6ff2](https://github.com/Breakfast-Galaxy-Studios/Soundboard/commit/08b6ff27f18f149ceaf76ded5013fd55173b9df4).
